name: flowwow
description: "A new Flutter project."

publish_to: 'Project' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.0.1
  url_launcher: ^6.2.1
  uuid: ^4.2.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  flutter_map: 4.0.0
  latlong2: ^0.8.0
  geolocator: ^10.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/shop/
    - assets/user/
    - assets/flowers/1flo.jpg
    - assets/flowers/2flo.jpg
    - assets/flowers/3flo.jpg
    - assets/flowers/4flo.jpg
    - assets/flowers/5flo.jpg
    - assets/flowers/6flo.jpg
    - assets/flowers/7flo.jpg
    - assets/flowers/decor.jpg
    - assets/flowers/gift.jpg


